# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Maven Publish

# on:
#  release:
#    types: [created]
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '21'
        distribution: 'microsoft'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1.3.0"
      with:
        fallback: 0.3.0 # Optional fallback tag to use when no tag can be found
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1.2.1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - name: 'Create new milestone'
      id: createmilestone
      uses: "WyriHaximus/github-action-create-milestone@v1.2.0"
      with:
        title: ${{ steps.semvers.outputs.patch }}
      env:
        GITHUB_TOKEN: "${{ secrets.TOKEN }}"

    - name: Build dependencies (xsm)
      run: mvn clean install -pl xsm -am -Dmaven.test.skip=true
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.TOKEN }}

    - name: Build with Maven
      run: mvn -f escali/pom.xml clean install -Dmaven.test.skip=true
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.TOKEN }}

    - name: Publish to GitHub Packages
      run: mvn deploy -pl escali -am -s $GITHUB_WORKSPACE/settings.xml -Dmaven.test.skip=true
      env:
        USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
